Repository felixsteinke/Motion-Planner, pull requests merged in 2022-05, with the labels that each got.

#22 Config Union
  app.py
  collisionspace.py
  configspace.py
Labels: type: enhancement, optional task

#26 Task pool edge collision
  project/configspace.py
Labels: type: enhancement

#27 Refactoring of full project to separate view
  README.md
  project/app.py
  project/app_window.py
  project/collisionspace.py
  project/configspace.py
  project/configspace_view.py
  project/controller.py
  project/option_window.py
  project/utils.py
  project/workspace.py
  project/workspace_calc.py
  project/workspace_view.py
Labels: type: documentation, type: enhancement

#30 Fixes after Rework
  project/collisionspace.py
  project/configspace.py
Labels: type: bug, type: enhancement

#31 fixed main window in background
  project/app.py
  project/option_window.py
Labels: type: bug, type: enhancement

#32 Rrt
  project/algorithm_rrt.py
  project/algorithm_sprm.py
  project/algorithms.py
  project/app.py
  project/app_window.py
  project/configspace.py
  project/configspace_view.py
  project/option_window.py
  project/utils.py
  requirements.txt
Labels: info: pre exam task
